name: window_location_href
description: Cross-platfrom window.location.href. Supports all platforms and is easy.
version: 2.0.0
homepage: https://pwa.ir
repository: https://github.com/olutter/window_location_href

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  web: ^1.1.1

dev_dependencies:
  test: ^1.26.0
  lints: ^6.0.0