name: window_location_href
description: Cross-platfrom window.location.href. Supports all platforms and is easy.
version: 1.0.1+2
homepage: https://pwa.ir
repository: https://github.com/xclud/window_location_href

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0